var searchData=
[
  ['p2g_1214',['p2g',['../namespaceCajita.html#af35c1fd6167a736a6a78cf742c2d6251',1,'Cajita']]],
  ['packarray_1215',['packArray',['../classCajita_1_1Halo.html#af9421d35f1b7e9de6f996779742493ea',1,'Cajita::Halo::packArray(const Kokkos::View&lt; char *, memory_space &gt; &amp;buffer, const Kokkos::View&lt; int **, memory_space &gt; &amp;steering, const int element_idx, const std::integral_constant&lt; std::size_t, 0 &gt;, const Cabana::ParameterPack&lt; ArrayViews... &gt; &amp;array_views)'],['../classCajita_1_1Halo.html#ae5b93e8998f49d1d0201cc90ac454aeb',1,'Cajita::Halo::packArray(const Kokkos::View&lt; char *, memory_space &gt; &amp;buffer, const Kokkos::View&lt; int **, memory_space &gt; &amp;steering, const int element_idx, const std::integral_constant&lt; std::size_t, N &gt;, const Cabana::ParameterPack&lt; ArrayViews... &gt; &amp;array_views)']]],
  ['packbuffer_1216',['packBuffer',['../classCajita_1_1Halo.html#af6d7a80dc844926cfec98d70730682e0',1,'Cajita::Halo']]],
  ['packelement_1217',['packElement',['../classCajita_1_1Halo.html#a69d63d32151d5377839488906d89f2c2',1,'Cajita::Halo::packElement(const Kokkos::View&lt; char *, memory_space &gt; &amp;buffer, const Kokkos::View&lt; int **, memory_space &gt; &amp;steering, const int element_idx, const ArrayView &amp;array_view)'],['../classCajita_1_1Halo.html#a63e0d4650d0db171a4c828a146b82aeb',1,'Cajita::Halo::packElement(const Kokkos::View&lt; char *, memory_space &gt; &amp;buffer, const Kokkos::View&lt; int **, memory_space &gt; &amp;steering, const int element_idx, const ArrayView &amp;array_view)']]],
  ['particlegridmigrate_1218',['particleGridMigrate',['../namespaceCajita.html#a27a15d0e5f51a41086538e27037a5262',1,'Cajita::particleGridMigrate(const LocalGridType &amp;local_grid, ParticlePositions &amp;positions, ParticleContainer &amp;particles, const int min_halo_width, const bool force_migrate=false)'],['../namespaceCajita.html#ac90f9c62f86663fdbd45327ba8537016',1,'Cajita::particleGridMigrate(const LocalGridType &amp;local_grid, const ParticlePositions &amp;positions, const ParticleContainer &amp;src_particles, ParticleContainer &amp;dst_particles, const int min_halo_width, const bool force_migrate=false)']]],
  ['permutation_1219',['permutation',['../classCabana_1_1LinkedCellList.html#a02fc6f7e0664efa8c1af34b45d2c57f8',1,'Cabana::LinkedCellList::permutation()'],['../classCabana_1_1BinningData.html#a3bc243700d37b13d90ec156f9da8283d',1,'Cabana::BinningData::permutation()']]],
  ['permute_1220',['permute',['../namespaceCabana.html#a02c3a57c3cd27a75094bbfa1be56145b',1,'Cabana::permute(const LinkedCellListType &amp;linked_cell_list, AoSoA_t &amp;aosoa, typename std::enable_if&lt;(is_linked_cell_list&lt; LinkedCellListType &gt;::value &amp;&amp;is_aosoa&lt; AoSoA_t &gt;::value), int &gt;::type *=0)'],['../namespaceCabana.html#a5a1ce7155c5c1185f46071b20d4dd332',1,'Cabana::permute(const LinkedCellListType &amp;linked_cell_list, SliceType &amp;slice, typename std::enable_if&lt;(is_linked_cell_list&lt; LinkedCellListType &gt;::value &amp;&amp;is_slice&lt; SliceType &gt;::value), int &gt;::type *=0)'],['../namespaceCabana.html#a824f296314f00ca8e121e6a26e2846db',1,'Cabana::permute(const BinningDataType &amp;binning_data, AoSoA_t &amp;aosoa, typename std::enable_if&lt;(is_binning_data&lt; BinningDataType &gt;::value &amp;&amp;is_aosoa&lt; AoSoA_t &gt;::value), int &gt;::type *=0)'],['../namespaceCabana.html#ab44a65c22331c71ed7cee721a41c54fc',1,'Cabana::permute(const BinningDataType &amp;binning_data, SliceType &amp;slice, typename std::enable_if&lt;(is_binning_data&lt; BinningDataType &gt;::value &amp;&amp;is_slice&lt; SliceType &gt;::value), int &gt;::type *=0)']]]
];
