coverage:
  precision: 1
  round: down
  range: "70...100"
ignore:
  - gtest/
  - cajita/unit_test/
  - core/unit_test/
  - core/example/tutorial
  - core/performance_test/benchmark
  - core/performance_test/peakflops
