var annotated_dup =
[
    [ "ArborX", null, [
      [ "AccessTraits< Cabana::Experimental::Impl::SubPositionsAndRadius< Positions >, PredicatesTag >", "structArborX_1_1AccessTraits_3_01Cabana_1_1Experimental_1_1Impl_1_1SubPositionsAndRadius_3_01Posaf575a813eeefa3e621d9c1ff9a6846b.html", "structArborX_1_1AccessTraits_3_01Cabana_1_1Experimental_1_1Impl_1_1SubPositionsAndRadius_3_01Posaf575a813eeefa3e621d9c1ff9a6846b" ],
      [ "AccessTraits< Positions, PrimitivesTag, std::enable_if_t< Cabana::is_slice< Positions >{}||Kokkos::is_view< Positions >{}> >", "structArborX_1_1AccessTraits_3_01Positions_00_01PrimitivesTag_00_01std_1_1enable__if__t_3_01Caba7933ad1c8460f725b910333ad2155912.html", "structArborX_1_1AccessTraits_3_01Positions_00_01PrimitivesTag_00_01std_1_1enable__if__t_3_01Caba7933ad1c8460f725b910333ad2155912" ]
    ] ],
    [ "Cabana", "namespaceCabana.html", [
      [ "Experimental", null, [
        [ "HDF5ParticleOutput", null, [
          [ "HDF5Config", "structCabana_1_1Experimental_1_1HDF5ParticleOutput_1_1HDF5Config.html", "structCabana_1_1Experimental_1_1HDF5ParticleOutput_1_1HDF5Config" ]
        ] ],
        [ "CrsGraph", "structCabana_1_1Experimental_1_1CrsGraph.html", "structCabana_1_1Experimental_1_1CrsGraph" ],
        [ "Dense", "structCabana_1_1Experimental_1_1Dense.html", "structCabana_1_1Experimental_1_1Dense" ]
      ] ],
      [ "Field", null, [
        [ "Matrix", "structCabana_1_1Field_1_1Matrix.html", "structCabana_1_1Field_1_1Matrix" ],
        [ "Position", "structCabana_1_1Field_1_1Position.html", null ],
        [ "Scalar", "structCabana_1_1Field_1_1Scalar.html", "structCabana_1_1Field_1_1Scalar" ],
        [ "Vector", "structCabana_1_1Field_1_1Vector.html", "structCabana_1_1Field_1_1Vector" ]
      ] ],
      [ "Grid", null, [
        [ "ArrayOp", null, [
          [ "DotFunctor", "structCabana_1_1Grid_1_1ArrayOp_1_1DotFunctor.html", "structCabana_1_1Grid_1_1ArrayOp_1_1DotFunctor" ],
          [ "Norm1Functor", "structCabana_1_1Grid_1_1ArrayOp_1_1Norm1Functor.html", "structCabana_1_1Grid_1_1ArrayOp_1_1Norm1Functor" ],
          [ "Norm2Functor", "structCabana_1_1Grid_1_1ArrayOp_1_1Norm2Functor.html", "structCabana_1_1Grid_1_1ArrayOp_1_1Norm2Functor" ],
          [ "NormInfFunctor", "structCabana_1_1Grid_1_1ArrayOp_1_1NormInfFunctor.html", "structCabana_1_1Grid_1_1ArrayOp_1_1NormInfFunctor" ]
        ] ],
        [ "Experimental", null, [
          [ "BovWriter", null, [
            [ "BovCentering", "structCabana_1_1Grid_1_1Experimental_1_1BovWriter_1_1BovCentering.html", null ],
            [ "BovCentering< Cell >", "structCabana_1_1Grid_1_1Experimental_1_1BovWriter_1_1BovCentering_3_01Cell_01_4.html", null ],
            [ "BovCentering< Node >", "structCabana_1_1Grid_1_1Experimental_1_1BovWriter_1_1BovCentering_3_01Node_01_4.html", null ],
            [ "BovFormat", "structCabana_1_1Grid_1_1Experimental_1_1BovWriter_1_1BovFormat.html", null ],
            [ "BovFormat< double >", "structCabana_1_1Grid_1_1Experimental_1_1BovWriter_1_1BovFormat_3_01double_01_4.html", null ],
            [ "BovFormat< float >", "structCabana_1_1Grid_1_1Experimental_1_1BovWriter_1_1BovFormat_3_01float_01_4.html", null ],
            [ "BovFormat< int >", "structCabana_1_1Grid_1_1Experimental_1_1BovWriter_1_1BovFormat_3_01int_01_4.html", null ],
            [ "BovFormat< short >", "structCabana_1_1Grid_1_1Experimental_1_1BovWriter_1_1BovFormat_3_01short_01_4.html", null ]
          ] ],
          [ "FastFourierTransform", "classCabana_1_1Grid_1_1Experimental_1_1FastFourierTransform.html", "classCabana_1_1Grid_1_1Experimental_1_1FastFourierTransform" ],
          [ "FastFourierTransformParams", "classCabana_1_1Grid_1_1Experimental_1_1FastFourierTransformParams.html", "classCabana_1_1Grid_1_1Experimental_1_1FastFourierTransformParams" ],
          [ "FFTBackendFFTW", "structCabana_1_1Grid_1_1Experimental_1_1FFTBackendFFTW.html", null ],
          [ "FFTBackendMKL", "structCabana_1_1Grid_1_1Experimental_1_1FFTBackendMKL.html", null ],
          [ "FFTScaleFull", "structCabana_1_1Grid_1_1Experimental_1_1FFTScaleFull.html", null ],
          [ "FFTScaleNone", "structCabana_1_1Grid_1_1Experimental_1_1FFTScaleNone.html", null ],
          [ "FFTScaleSymmetric", "structCabana_1_1Grid_1_1Experimental_1_1FFTScaleSymmetric.html", null ],
          [ "HeffteFastFourierTransform", "classCabana_1_1Grid_1_1Experimental_1_1HeffteFastFourierTransform.html", "classCabana_1_1Grid_1_1Experimental_1_1HeffteFastFourierTransform" ],
          [ "is_matching_array", "structCabana_1_1Grid_1_1Experimental_1_1is__matching__array.html", null ],
          [ "is_matching_array< ArrayEntity, ArrayMesh, ArrayMemorySpace, ArrayScalar, Entity, Mesh, MemorySpace, Scalar, typename std::enable_if< std::is_same< ArrayEntity, Entity >::value &&std::is_same< ArrayMesh, Mesh >::value &&std::is_same< ArrayMemorySpace, MemorySpace >::value >::type >", "structCabana_1_1Grid_1_1Experimental_1_1is__matching__array_3_01ArrayEntity_00_01ArrayMesh_00_01011c8202aae6c4055086b636991c1366.html", null ],
          [ "is_sparse_array", "structCabana_1_1Grid_1_1Experimental_1_1is__sparse__array.html", null ],
          [ "is_sparse_array< const SparseArray< DataTypes, MemorySpace, EntityType, MeshType, SparseMapType > >", "structCabana_1_1Grid_1_1Experimental_1_1is__sparse__array_3_01const_01SparseArray_3_01DataTypes_0938a7b8567d673f492a8d640d48a873.html", null ],
          [ "is_sparse_array< SparseArray< DataTypes, MemorySpace, EntityType, MeshType, SparseMapType > >", "structCabana_1_1Grid_1_1Experimental_1_1is__sparse__array_3_01SparseArray_3_01DataTypes_00_01Mem6647a7f2eee31026553b5236de97baaa.html", null ],
          [ "is_sparse_array_layout", "structCabana_1_1Grid_1_1Experimental_1_1is__sparse__array__layout.html", null ],
          [ "is_sparse_array_layout< const SparseArrayLayout< DataTypes, EntityType, MeshType, SparseMapType > >", "structCabana_1_1Grid_1_1Experimental_1_1is__sparse__array__layout_3_01const_01SparseArrayLayout_548a2ce48d4c7be40de99b5176c64851.html", null ],
          [ "is_sparse_array_layout< SparseArrayLayout< DataTypes, EntityType, MeshType, SparseMapType > >", "structCabana_1_1Grid_1_1Experimental_1_1is__sparse__array__layout_3_01SparseArrayLayout_3_01Datae4ed42c66fe8eb57266f1516fcc70ba5.html", null ],
          [ "LoadBalancer", "classCabana_1_1Grid_1_1Experimental_1_1LoadBalancer.html", null ],
          [ "LoadBalancer< UniformMesh< Scalar, NumSpaceDim > >", "classCabana_1_1Grid_1_1Experimental_1_1LoadBalancer_3_01UniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", "classCabana_1_1Grid_1_1Experimental_1_1LoadBalancer_3_01UniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4" ],
          [ "LocalGrid", "classCabana_1_1Grid_1_1Experimental_1_1LocalGrid.html", null ],
          [ "LocalGrid< SparseMesh< Scalar, NumSpaceDim > >", "classCabana_1_1Grid_1_1Experimental_1_1LocalGrid_3_01SparseMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", "classCabana_1_1Grid_1_1Experimental_1_1LocalGrid_3_01SparseMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4" ],
          [ "SparseArray", "classCabana_1_1Grid_1_1Experimental_1_1SparseArray.html", "classCabana_1_1Grid_1_1Experimental_1_1SparseArray" ],
          [ "SparseArrayLayout", "classCabana_1_1Grid_1_1Experimental_1_1SparseArrayLayout.html", "classCabana_1_1Grid_1_1Experimental_1_1SparseArrayLayout" ],
          [ "SparseHalo", "classCabana_1_1Grid_1_1Experimental_1_1SparseHalo.html", "classCabana_1_1Grid_1_1Experimental_1_1SparseHalo" ]
        ] ],
        [ "IndexConversion", null, [
          [ "L2G", "structCabana_1_1Grid_1_1IndexConversion_1_1L2G.html", "structCabana_1_1Grid_1_1IndexConversion_1_1L2G" ]
        ] ],
        [ "P2G", null, [
          [ "is_scatter_view", "structCabana_1_1Grid_1_1P2G_1_1is__scatter__view.html", null ]
        ] ],
        [ "ScatterReduce", null, [
          [ "Max", "structCabana_1_1Grid_1_1ScatterReduce_1_1Max.html", null ],
          [ "Min", "structCabana_1_1Grid_1_1ScatterReduce_1_1Min.html", null ],
          [ "Replace", "structCabana_1_1Grid_1_1ScatterReduce_1_1Replace.html", null ],
          [ "Sum", "structCabana_1_1Grid_1_1ScatterReduce_1_1Sum.html", null ]
        ] ],
        [ "Array", "classCabana_1_1Grid_1_1Array.html", "classCabana_1_1Grid_1_1Array" ],
        [ "ArrayLayout", "classCabana_1_1Grid_1_1ArrayLayout.html", "classCabana_1_1Grid_1_1ArrayLayout" ],
        [ "ArrayPackMemorySpace", "structCabana_1_1Grid_1_1ArrayPackMemorySpace.html", "structCabana_1_1Grid_1_1ArrayPackMemorySpace" ],
        [ "BlockMap", "classCabana_1_1Grid_1_1BlockMap.html", "classCabana_1_1Grid_1_1BlockMap" ],
        [ "BlockPartitioner", "classCabana_1_1Grid_1_1BlockPartitioner.html", "classCabana_1_1Grid_1_1BlockPartitioner" ],
        [ "Cell", "structCabana_1_1Grid_1_1Cell.html", null ],
        [ "Dim", "structCabana_1_1Grid_1_1Dim.html", "structCabana_1_1Grid_1_1Dim" ],
        [ "DimBlockPartitioner", "classCabana_1_1Grid_1_1DimBlockPartitioner.html", "classCabana_1_1Grid_1_1DimBlockPartitioner" ],
        [ "Edge", "structCabana_1_1Grid_1_1Edge.html", null ],
        [ "Edge< Dim::I >", "structCabana_1_1Grid_1_1Edge_3_01Dim_1_1I_01_4.html", null ],
        [ "Edge< Dim::J >", "structCabana_1_1Grid_1_1Edge_3_01Dim_1_1J_01_4.html", null ],
        [ "Edge< Dim::K >", "structCabana_1_1Grid_1_1Edge_3_01Dim_1_1K_01_4.html", null ],
        [ "Face", "structCabana_1_1Grid_1_1Face.html", null ],
        [ "Face< Dim::I >", "structCabana_1_1Grid_1_1Face_3_01Dim_1_1I_01_4.html", null ],
        [ "Face< Dim::J >", "structCabana_1_1Grid_1_1Face_3_01Dim_1_1J_01_4.html", null ],
        [ "Face< Dim::K >", "structCabana_1_1Grid_1_1Face_3_01Dim_1_1K_01_4.html", null ],
        [ "FaceHaloPattern", "classCabana_1_1Grid_1_1FaceHaloPattern.html", null ],
        [ "FaceHaloPattern< 2 >", "classCabana_1_1Grid_1_1FaceHaloPattern_3_012_01_4.html", null ],
        [ "FaceHaloPattern< 3 >", "classCabana_1_1Grid_1_1FaceHaloPattern_3_013_01_4.html", null ],
        [ "Ghost", "structCabana_1_1Grid_1_1Ghost.html", null ],
        [ "Global", "structCabana_1_1Grid_1_1Global.html", null ],
        [ "GlobalGrid", "classCabana_1_1Grid_1_1GlobalGrid.html", "classCabana_1_1Grid_1_1GlobalGrid" ],
        [ "GlobalMesh", "classCabana_1_1Grid_1_1GlobalMesh.html", "classCabana_1_1Grid_1_1GlobalMesh" ],
        [ "GlobalMesh< NonUniformMesh< Scalar, 2 > >", "classCabana_1_1Grid_1_1GlobalMesh_3_01NonUniformMesh_3_01Scalar_00_012_01_4_01_4.html", "classCabana_1_1Grid_1_1GlobalMesh_3_01NonUniformMesh_3_01Scalar_00_012_01_4_01_4" ],
        [ "GlobalMesh< NonUniformMesh< Scalar, 3 > >", "classCabana_1_1Grid_1_1GlobalMesh_3_01NonUniformMesh_3_01Scalar_00_013_01_4_01_4.html", "classCabana_1_1Grid_1_1GlobalMesh_3_01NonUniformMesh_3_01Scalar_00_013_01_4_01_4" ],
        [ "GlobalParticleComm", "classCabana_1_1Grid_1_1GlobalParticleComm.html", "classCabana_1_1Grid_1_1GlobalParticleComm" ],
        [ "Halo", "classCabana_1_1Grid_1_1Halo.html", "classCabana_1_1Grid_1_1Halo" ],
        [ "HaloPattern", "classCabana_1_1Grid_1_1HaloPattern.html", "classCabana_1_1Grid_1_1HaloPattern" ],
        [ "has_spline_tag", "structCabana_1_1Grid_1_1has__spline__tag.html", null ],
        [ "HashKey2TileID", "structCabana_1_1Grid_1_1HashKey2TileID.html", null ],
        [ "HypreIsCompatibleWithMemorySpace", "structCabana_1_1Grid_1_1HypreIsCompatibleWithMemorySpace.html", null ],
        [ "HypreIsCompatibleWithMemorySpace< Kokkos::HostSpace >", "structCabana_1_1Grid_1_1HypreIsCompatibleWithMemorySpace_3_01Kokkos_1_1HostSpace_01_4.html", null ],
        [ "HypreSemiStructBiCGSTAB", "classCabana_1_1Grid_1_1HypreSemiStructBiCGSTAB.html", "classCabana_1_1Grid_1_1HypreSemiStructBiCGSTAB" ],
        [ "HypreSemiStructDiagonal", "classCabana_1_1Grid_1_1HypreSemiStructDiagonal.html", "classCabana_1_1Grid_1_1HypreSemiStructDiagonal" ],
        [ "HypreSemiStructGMRES", "classCabana_1_1Grid_1_1HypreSemiStructGMRES.html", "classCabana_1_1Grid_1_1HypreSemiStructGMRES" ],
        [ "HypreSemiStructPCG", "classCabana_1_1Grid_1_1HypreSemiStructPCG.html", "classCabana_1_1Grid_1_1HypreSemiStructPCG" ],
        [ "HypreSemiStructuredSolver", "classCabana_1_1Grid_1_1HypreSemiStructuredSolver.html", "classCabana_1_1Grid_1_1HypreSemiStructuredSolver" ],
        [ "HypreStructBiCGSTAB", "classCabana_1_1Grid_1_1HypreStructBiCGSTAB.html", "classCabana_1_1Grid_1_1HypreStructBiCGSTAB" ],
        [ "HypreStructDiagonal", "classCabana_1_1Grid_1_1HypreStructDiagonal.html", "classCabana_1_1Grid_1_1HypreStructDiagonal" ],
        [ "HypreStructGMRES", "classCabana_1_1Grid_1_1HypreStructGMRES.html", "classCabana_1_1Grid_1_1HypreStructGMRES" ],
        [ "HypreStructJacobi", "classCabana_1_1Grid_1_1HypreStructJacobi.html", "classCabana_1_1Grid_1_1HypreStructJacobi" ],
        [ "HypreStructPCG", "classCabana_1_1Grid_1_1HypreStructPCG.html", "classCabana_1_1Grid_1_1HypreStructPCG" ],
        [ "HypreStructPFMG", "classCabana_1_1Grid_1_1HypreStructPFMG.html", "classCabana_1_1Grid_1_1HypreStructPFMG" ],
        [ "HypreStructSMG", "classCabana_1_1Grid_1_1HypreStructSMG.html", "classCabana_1_1Grid_1_1HypreStructSMG" ],
        [ "HypreStructuredSolver", "classCabana_1_1Grid_1_1HypreStructuredSolver.html", "classCabana_1_1Grid_1_1HypreStructuredSolver" ],
        [ "IndexSpace", "classCabana_1_1Grid_1_1IndexSpace.html", "classCabana_1_1Grid_1_1IndexSpace" ],
        [ "is_array", "structCabana_1_1Grid_1_1is__array.html", null ],
        [ "is_array< Array< Scalar, EntityType, MeshType, Params... > >", "structCabana_1_1Grid_1_1is__array_3_01Array_3_01Scalar_00_01EntityType_00_01MeshType_00_01Params_8_8_8_01_4_01_4.html", null ],
        [ "is_array< const Array< Scalar, EntityType, MeshType, Params... > >", "structCabana_1_1Grid_1_1is__array_3_01const_01Array_3_01Scalar_00_01EntityType_00_01MeshType_00_01Params_8_8_8_01_4_01_4.html", null ],
        [ "is_array_layout", "structCabana_1_1Grid_1_1is__array__layout.html", null ],
        [ "is_array_layout< ArrayLayout< EntityType, MeshType > >", "structCabana_1_1Grid_1_1is__array__layout_3_01ArrayLayout_3_01EntityType_00_01MeshType_01_4_01_4.html", null ],
        [ "is_array_layout< const ArrayLayout< EntityType, MeshType > >", "structCabana_1_1Grid_1_1is__array__layout_3_01const_01ArrayLayout_3_01EntityType_00_01MeshType_01_4_01_4.html", null ],
        [ "is_particle_list", "structCabana_1_1Grid_1_1is__particle__list.html", null ],
        [ "is_particle_list_impl", "structCabana_1_1Grid_1_1is__particle__list__impl.html", null ],
        [ "is_particle_list_impl< ParticleList< MemorySpace, VectorLength, FieldTags... > >", "structCabana_1_1Grid_1_1is__particle__list__impl_3_01ParticleList_3_01MemorySpace_00_01VectorLen9691ba23fa9dee34013ce18dde8aacc7.html", null ],
        [ "isCell", "structCabana_1_1Grid_1_1isCell.html", null ],
        [ "isCell< Cell >", "structCabana_1_1Grid_1_1isCell_3_01Cell_01_4.html", null ],
        [ "isCell< const Cell >", "structCabana_1_1Grid_1_1isCell_3_01const_01Cell_01_4.html", null ],
        [ "isEdge", "structCabana_1_1Grid_1_1isEdge.html", null ],
        [ "isEdge< const Edge< Dir > >", "structCabana_1_1Grid_1_1isEdge_3_01const_01Edge_3_01Dir_01_4_01_4.html", null ],
        [ "isEdge< Edge< Dir > >", "structCabana_1_1Grid_1_1isEdge_3_01Edge_3_01Dir_01_4_01_4.html", null ],
        [ "isFace", "structCabana_1_1Grid_1_1isFace.html", null ],
        [ "isFace< const Face< Dir > >", "structCabana_1_1Grid_1_1isFace_3_01const_01Face_3_01Dir_01_4_01_4.html", null ],
        [ "isFace< Face< Dir > >", "structCabana_1_1Grid_1_1isFace_3_01Face_3_01Dir_01_4_01_4.html", null ],
        [ "isMeshType", "structCabana_1_1Grid_1_1isMeshType.html", null ],
        [ "isMeshType< const NonUniformMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isMeshType_3_01const_01NonUniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isMeshType< const SparseMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isMeshType_3_01const_01SparseMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isMeshType< const UniformMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isMeshType_3_01const_01UniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isMeshType< NonUniformMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isMeshType_3_01NonUniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isMeshType< SparseMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isMeshType_3_01SparseMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isMeshType< UniformMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isMeshType_3_01UniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isNode", "structCabana_1_1Grid_1_1isNode.html", null ],
        [ "isNode< const Node >", "structCabana_1_1Grid_1_1isNode_3_01const_01Node_01_4.html", null ],
        [ "isNode< Node >", "structCabana_1_1Grid_1_1isNode_3_01Node_01_4.html", null ],
        [ "isNonUniformMesh", "structCabana_1_1Grid_1_1isNonUniformMesh.html", null ],
        [ "isNonUniformMesh< const NonUniformMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isNonUniformMesh_3_01const_01NonUniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isNonUniformMesh< NonUniformMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isNonUniformMesh_3_01NonUniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isSparseMesh", "structCabana_1_1Grid_1_1isSparseMesh.html", null ],
        [ "isSparseMesh< const SparseMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isSparseMesh_3_01const_01SparseMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isSparseMesh< SparseMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isSparseMesh_3_01SparseMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isUniformMesh", "structCabana_1_1Grid_1_1isUniformMesh.html", null ],
        [ "isUniformMesh< const UniformMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isUniformMesh_3_01const_01UniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "isUniformMesh< UniformMesh< Scalar, NumSpaceDim > >", "structCabana_1_1Grid_1_1isUniformMesh_3_01UniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", null ],
        [ "Local", "structCabana_1_1Grid_1_1Local.html", null ],
        [ "LocalGrid", "classCabana_1_1Grid_1_1LocalGrid.html", "classCabana_1_1Grid_1_1LocalGrid" ],
        [ "LocalMesh", "classCabana_1_1Grid_1_1LocalMesh.html", null ],
        [ "LocalMesh< MemorySpace, NonUniformMesh< Scalar, NumSpaceDim > >", "classCabana_1_1Grid_1_1LocalMesh_3_01MemorySpace_00_01NonUniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", "classCabana_1_1Grid_1_1LocalMesh_3_01MemorySpace_00_01NonUniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4" ],
        [ "LocalMesh< MemorySpace, UniformMesh< Scalar, NumSpaceDim > >", "classCabana_1_1Grid_1_1LocalMesh_3_01MemorySpace_00_01UniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4.html", "classCabana_1_1Grid_1_1LocalMesh_3_01MemorySpace_00_01UniformMesh_3_01Scalar_00_01NumSpaceDim_01_4_01_4" ],
        [ "ManualBlockPartitioner", "classCabana_1_1Grid_1_1ManualBlockPartitioner.html", "classCabana_1_1Grid_1_1ManualBlockPartitioner" ],
        [ "MpiTraits", "structCabana_1_1Grid_1_1MpiTraits.html", null ],
        [ "MpiTraits< char >", "structCabana_1_1Grid_1_1MpiTraits_3_01char_01_4.html", null ],
        [ "MpiTraits< double >", "structCabana_1_1Grid_1_1MpiTraits_3_01double_01_4.html", null ],
        [ "MpiTraits< float >", "structCabana_1_1Grid_1_1MpiTraits_3_01float_01_4.html", null ],
        [ "MpiTraits< int >", "structCabana_1_1Grid_1_1MpiTraits_3_01int_01_4.html", null ],
        [ "MpiTraits< long >", "structCabana_1_1Grid_1_1MpiTraits_3_01long_01_4.html", null ],
        [ "Node", "structCabana_1_1Grid_1_1Node.html", null ],
        [ "NodeHaloPattern", "classCabana_1_1Grid_1_1NodeHaloPattern.html", null ],
        [ "NodeHaloPattern< 2 >", "classCabana_1_1Grid_1_1NodeHaloPattern_3_012_01_4.html", null ],
        [ "NodeHaloPattern< 3 >", "classCabana_1_1Grid_1_1NodeHaloPattern_3_013_01_4.html", null ],
        [ "NonUniformMesh", "structCabana_1_1Grid_1_1NonUniformMesh.html", "structCabana_1_1Grid_1_1NonUniformMesh" ],
        [ "Own", "structCabana_1_1Grid_1_1Own.html", null ],
        [ "ParticleList", "classCabana_1_1Grid_1_1ParticleList.html", "classCabana_1_1Grid_1_1ParticleList" ],
        [ "ReferenceConjugateGradient", "classCabana_1_1Grid_1_1ReferenceConjugateGradient.html", "classCabana_1_1Grid_1_1ReferenceConjugateGradient" ],
        [ "ReferenceStructuredSolver", "classCabana_1_1Grid_1_1ReferenceStructuredSolver.html", "classCabana_1_1Grid_1_1ReferenceStructuredSolver" ],
        [ "ScalarGradientG2P", "structCabana_1_1Grid_1_1ScalarGradientG2P.html", "structCabana_1_1Grid_1_1ScalarGradientG2P" ],
        [ "ScalarGradientP2G", "structCabana_1_1Grid_1_1ScalarGradientP2G.html", "structCabana_1_1Grid_1_1ScalarGradientP2G" ],
        [ "ScalarValueG2P", "structCabana_1_1Grid_1_1ScalarValueG2P.html", "structCabana_1_1Grid_1_1ScalarValueG2P" ],
        [ "ScalarValueP2G", "structCabana_1_1Grid_1_1ScalarValueP2G.html", "structCabana_1_1Grid_1_1ScalarValueP2G" ],
        [ "SparseDimPartitioner", "classCabana_1_1Grid_1_1SparseDimPartitioner.html", "classCabana_1_1Grid_1_1SparseDimPartitioner" ],
        [ "SparseMap", "classCabana_1_1Grid_1_1SparseMap.html", "classCabana_1_1Grid_1_1SparseMap" ],
        [ "SparseMesh", "structCabana_1_1Grid_1_1SparseMesh.html", "structCabana_1_1Grid_1_1SparseMesh" ],
        [ "Spline", "structCabana_1_1Grid_1_1Spline.html", null ],
        [ "Spline< 0 >", "structCabana_1_1Grid_1_1Spline_3_010_01_4.html", null ],
        [ "Spline< 1 >", "structCabana_1_1Grid_1_1Spline_3_011_01_4.html", null ],
        [ "Spline< 2 >", "structCabana_1_1Grid_1_1Spline_3_012_01_4.html", null ],
        [ "Spline< 3 >", "structCabana_1_1Grid_1_1Spline_3_013_01_4.html", null ],
        [ "Spline< 4 >", "structCabana_1_1Grid_1_1Spline_3_014_01_4.html", null ],
        [ "Spline< 5 >", "structCabana_1_1Grid_1_1Spline_3_015_01_4.html", null ],
        [ "Spline< 6 >", "structCabana_1_1Grid_1_1Spline_3_016_01_4.html", null ],
        [ "SplineData", "structCabana_1_1Grid_1_1SplineData.html", null ],
        [ "SplineData< Scalar, Order, NumSpaceDim, EntityType, SplineDataMemberTypes< Tags... > >", "structCabana_1_1Grid_1_1SplineData_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01EntityType_00_01Sa7fa7ff4e86d570f0b3660ebbf561858.html", "structCabana_1_1Grid_1_1SplineData_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01EntityType_00_01Sa7fa7ff4e86d570f0b3660ebbf561858" ],
        [ "SplineData< Scalar, Order, NumSpaceDim, EntityType, void >", "structCabana_1_1Grid_1_1SplineData_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01EntityType_00_01void_01_4.html", "structCabana_1_1Grid_1_1SplineData_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01EntityType_00_01void_01_4" ],
        [ "SplineDataMember", "structCabana_1_1Grid_1_1SplineDataMember.html", null ],
        [ "SplineDataMember< Scalar, Order, NumSpaceDim, SplineLogicalPosition >", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplineLogicalPosition_01_4.html", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplineLogicalPosition_01_4" ],
        [ "SplineDataMember< Scalar, Order, NumSpaceDim, SplinePhysicalCellSize >", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplinePhysicalCellSize_01_4.html", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplinePhysicalCellSize_01_4" ],
        [ "SplineDataMember< Scalar, Order, NumSpaceDim, SplinePhysicalDistance >", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplinePhysicalDistance_01_4.html", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplinePhysicalDistance_01_4" ],
        [ "SplineDataMember< Scalar, Order, NumSpaceDim, SplineWeightPhysicalGradients >", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplineWeightPhysicalGradients_01_4.html", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplineWeightPhysicalGradients_01_4" ],
        [ "SplineDataMember< Scalar, Order, NumSpaceDim, SplineWeightValues >", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplineWeightValues_01_4.html", "structCabana_1_1Grid_1_1SplineDataMember_3_01Scalar_00_01Order_00_01NumSpaceDim_00_01SplineWeightValues_01_4" ],
        [ "SplineDataMemberTypes", "structCabana_1_1Grid_1_1SplineDataMemberTypes.html", null ],
        [ "SplineLogicalPosition", "structCabana_1_1Grid_1_1SplineLogicalPosition.html", null ],
        [ "SplinePhysicalCellSize", "structCabana_1_1Grid_1_1SplinePhysicalCellSize.html", null ],
        [ "SplinePhysicalDistance", "structCabana_1_1Grid_1_1SplinePhysicalDistance.html", null ],
        [ "SplineWeightPhysicalGradients", "structCabana_1_1Grid_1_1SplineWeightPhysicalGradients.html", null ],
        [ "SplineWeightValues", "structCabana_1_1Grid_1_1SplineWeightValues.html", null ],
        [ "TensorDivergenceP2G", "structCabana_1_1Grid_1_1TensorDivergenceP2G.html", "structCabana_1_1Grid_1_1TensorDivergenceP2G" ],
        [ "TileID2HashKey", "structCabana_1_1Grid_1_1TileID2HashKey.html", null ],
        [ "TileIndexSpace", "classCabana_1_1Grid_1_1TileIndexSpace.html", "classCabana_1_1Grid_1_1TileIndexSpace" ],
        [ "TileMap", "classCabana_1_1Grid_1_1TileMap.html", null ],
        [ "UniformMesh", "structCabana_1_1Grid_1_1UniformMesh.html", "structCabana_1_1Grid_1_1UniformMesh" ],
        [ "VectorDivergenceG2P", "structCabana_1_1Grid_1_1VectorDivergenceG2P.html", "structCabana_1_1Grid_1_1VectorDivergenceG2P" ],
        [ "VectorDivergenceP2G", "structCabana_1_1Grid_1_1VectorDivergenceP2G.html", "structCabana_1_1Grid_1_1VectorDivergenceP2G" ],
        [ "VectorGradientG2P", "structCabana_1_1Grid_1_1VectorGradientG2P.html", "structCabana_1_1Grid_1_1VectorGradientG2P" ],
        [ "VectorValueG2P", "structCabana_1_1Grid_1_1VectorValueG2P.html", "structCabana_1_1Grid_1_1VectorValueG2P" ],
        [ "VectorValueP2G", "structCabana_1_1Grid_1_1VectorValueP2G.html", "structCabana_1_1Grid_1_1VectorValueP2G" ]
      ] ],
      [ "Impl", null, [
        [ "Index", "classCabana_1_1Impl_1_1Index.html", null ],
        [ "PerformanceTraits", "classCabana_1_1Impl_1_1PerformanceTraits.html", null ]
      ] ],
      [ "AoSoA", "classCabana_1_1AoSoA.html", "classCabana_1_1AoSoA" ],
      [ "AtomicAccessMemory", "structCabana_1_1AtomicAccessMemory.html", "structCabana_1_1AtomicAccessMemory" ],
      [ "BinningData", "classCabana_1_1BinningData.html", "classCabana_1_1BinningData" ],
      [ "CheckMemberTypes", "structCabana_1_1CheckMemberTypes.html", null ],
      [ "CheckMemberTypes< MemberTypes< Types... > >", "structCabana_1_1CheckMemberTypes_3_01MemberTypes_3_01Types_8_8_8_01_4_01_4.html", null ],
      [ "CommunicationData", "classCabana_1_1CommunicationData.html", "classCabana_1_1CommunicationData" ],
      [ "CommunicationDataAoSoA", "structCabana_1_1CommunicationDataAoSoA.html", "structCabana_1_1CommunicationDataAoSoA" ],
      [ "CommunicationDataSlice", "structCabana_1_1CommunicationDataSlice.html", "structCabana_1_1CommunicationDataSlice" ],
      [ "CommunicationPlan", "classCabana_1_1CommunicationPlan.html", "classCabana_1_1CommunicationPlan" ],
      [ "DefaultAccessMemory", "structCabana_1_1DefaultAccessMemory.html", "structCabana_1_1DefaultAccessMemory" ],
      [ "Distributor", "classCabana_1_1Distributor.html", "classCabana_1_1Distributor" ],
      [ "FirstNeighborsTag", "classCabana_1_1FirstNeighborsTag.html", null ],
      [ "FullNeighborTag", "classCabana_1_1FullNeighborTag.html", null ],
      [ "Gather", "classCabana_1_1Gather.html", null ],
      [ "Gather< HaloType, AoSoAType, typename std::enable_if< is_aosoa< AoSoAType >::value >::type >", "classCabana_1_1Gather_3_01HaloType_00_01AoSoAType_00_01typename_01std_1_1enable__if_3_01is__aoso666e08a1494152c80218c785a19e78d3.html", "classCabana_1_1Gather_3_01HaloType_00_01AoSoAType_00_01typename_01std_1_1enable__if_3_01is__aoso666e08a1494152c80218c785a19e78d3" ],
      [ "Gather< HaloType, SliceType, typename std::enable_if< is_slice< SliceType >::value >::type >", "classCabana_1_1Gather_3_01HaloType_00_01SliceType_00_01typename_01std_1_1enable__if_3_01is__slica420051aad1e71fccbd290130c9a8cef.html", "classCabana_1_1Gather_3_01HaloType_00_01SliceType_00_01typename_01std_1_1enable__if_3_01is__slica420051aad1e71fccbd290130c9a8cef" ],
      [ "HalfNeighborTag", "classCabana_1_1HalfNeighborTag.html", null ],
      [ "Halo", "classCabana_1_1Halo.html", "classCabana_1_1Halo" ],
      [ "InitRandom", "structCabana_1_1InitRandom.html", null ],
      [ "InitUniform", "structCabana_1_1InitUniform.html", null ],
      [ "is_accessible_from", "structCabana_1_1is__accessible__from.html", null ],
      [ "is_accessible_from< MemorySpace, ExecutionSpace, std::enable_if_t< Kokkos::SpaceAccessibility< ExecutionSpace, MemorySpace >::accessible > >", "structCabana_1_1is__accessible__from_3_01MemorySpace_00_01ExecutionSpace_00_01std_1_1enable__if_96534d0f81e01b006272bb63cf2f3dd3.html", null ],
      [ "is_aosoa", "structCabana_1_1is__aosoa.html", null ],
      [ "is_binning_data< const BinningData< MemorySpace > >", "structCabana_1_1is__binning__data_3_01const_01BinningData_3_01MemorySpace_01_4_01_4.html", null ],
      [ "is_distributor", "structCabana_1_1is__distributor.html", null ],
      [ "is_halo", "structCabana_1_1is__halo.html", null ],
      [ "is_linked_cell_list", "structCabana_1_1is__linked__cell__list.html", null ],
      [ "is_member_types", "structCabana_1_1is__member__types.html", null ],
      [ "is_memory_access_tag", "structCabana_1_1is__memory__access__tag.html", null ],
      [ "is_memory_access_tag< AtomicAccessMemory >", "structCabana_1_1is__memory__access__tag_3_01AtomicAccessMemory_01_4.html", null ],
      [ "is_memory_access_tag< DefaultAccessMemory >", "structCabana_1_1is__memory__access__tag_3_01DefaultAccessMemory_01_4.html", null ],
      [ "is_memory_access_tag< RandomAccessMemory >", "structCabana_1_1is__memory__access__tag_3_01RandomAccessMemory_01_4.html", null ],
      [ "is_parameter_pack", "structCabana_1_1is__parameter__pack.html", null ],
      [ "is_particle_list", "structCabana_1_1is__particle__list.html", null ],
      [ "is_particle_list_impl", "structCabana_1_1is__particle__list__impl.html", null ],
      [ "is_particle_list_impl< ParticleList< MemorySpace, VectorLength, FieldTags... > >", "structCabana_1_1is__particle__list__impl_3_01ParticleList_3_01MemorySpace_00_01VectorLength_00_01FieldTags_8_8_8_01_4_01_4.html", null ],
      [ "is_slice", "structCabana_1_1is__slice.html", null ],
      [ "is_soa", "structCabana_1_1is__soa.html", null ],
      [ "is_tuple", "structCabana_1_1is__tuple.html", null ],
      [ "LinkedCellList", "classCabana_1_1LinkedCellList.html", "classCabana_1_1LinkedCellList" ],
      [ "LinkedCellStencil", "structCabana_1_1LinkedCellStencil.html", "structCabana_1_1LinkedCellStencil" ],
      [ "MemberTypeAtIndex", "structCabana_1_1MemberTypeAtIndex.html", null ],
      [ "MemberTypeAtIndex< M, MemberTypes< Types... > >", "structCabana_1_1MemberTypeAtIndex_3_01M_00_01MemberTypes_3_01Types_8_8_8_01_4_01_4.html", "structCabana_1_1MemberTypeAtIndex_3_01M_00_01MemberTypes_3_01Types_8_8_8_01_4_01_4" ],
      [ "MemberTypes", "structCabana_1_1MemberTypes.html", null ],
      [ "NeighborDiscriminator", "classCabana_1_1NeighborDiscriminator.html", null ],
      [ "NeighborDiscriminator< FullNeighborTag >", "classCabana_1_1NeighborDiscriminator_3_01FullNeighborTag_01_4.html", null ],
      [ "NeighborDiscriminator< HalfNeighborTag >", "classCabana_1_1NeighborDiscriminator_3_01HalfNeighborTag_01_4.html", null ],
      [ "NeighborList", "classCabana_1_1NeighborList.html", "classCabana_1_1NeighborList" ],
      [ "NeighborList< Experimental::CrsGraph< MemorySpace, Tag > >", "classCabana_1_1NeighborList_3_01Experimental_1_1CrsGraph_3_01MemorySpace_00_01Tag_01_4_01_4.html", "classCabana_1_1NeighborList_3_01Experimental_1_1CrsGraph_3_01MemorySpace_00_01Tag_01_4_01_4" ],
      [ "NeighborList< Experimental::Dense< MemorySpace, Tag > >", "classCabana_1_1NeighborList_3_01Experimental_1_1Dense_3_01MemorySpace_00_01Tag_01_4_01_4.html", "classCabana_1_1NeighborList_3_01Experimental_1_1Dense_3_01MemorySpace_00_01Tag_01_4_01_4" ],
      [ "NeighborList< LinkedCellList< MemorySpace, Scalar > >", "classCabana_1_1NeighborList_3_01LinkedCellList_3_01MemorySpace_00_01Scalar_01_4_01_4.html", "classCabana_1_1NeighborList_3_01LinkedCellList_3_01MemorySpace_00_01Scalar_01_4_01_4" ],
      [ "NeighborList< VerletList< MemorySpace, AlgorithmTag, VerletLayout2D, BuildTag > >", "classCabana_1_1NeighborList_3_01VerletList_3_01MemorySpace_00_01AlgorithmTag_00_01VerletLayout2D_00_01BuildTag_01_4_01_4.html", "classCabana_1_1NeighborList_3_01VerletList_3_01MemorySpace_00_01AlgorithmTag_00_01VerletLayout2D_00_01BuildTag_01_4_01_4" ],
      [ "NeighborList< VerletList< MemorySpace, AlgorithmTag, VerletLayoutCSR, BuildTag > >", "classCabana_1_1NeighborList_3_01VerletList_3_01MemorySpace_00_01AlgorithmTag_00_01VerletLayoutCSR_00_01BuildTag_01_4_01_4.html", "classCabana_1_1NeighborList_3_01VerletList_3_01MemorySpace_00_01AlgorithmTag_00_01VerletLayoutCSR_00_01BuildTag_01_4_01_4" ],
      [ "PackTypeAtIndex", "structCabana_1_1PackTypeAtIndex.html", "structCabana_1_1PackTypeAtIndex" ],
      [ "ParameterPack", "structCabana_1_1ParameterPack.html", "structCabana_1_1ParameterPack" ],
      [ "ParameterPackElement", "structCabana_1_1ParameterPackElement.html", "structCabana_1_1ParameterPackElement" ],
      [ "Particle", "structCabana_1_1Particle.html", "structCabana_1_1Particle" ],
      [ "ParticleList", "classCabana_1_1ParticleList.html", "classCabana_1_1ParticleList" ],
      [ "ParticleTraits", "structCabana_1_1ParticleTraits.html", "structCabana_1_1ParticleTraits" ],
      [ "ParticleView", "structCabana_1_1ParticleView.html", "structCabana_1_1ParticleView" ],
      [ "RandomAccessMemory", "structCabana_1_1RandomAccessMemory.html", "structCabana_1_1RandomAccessMemory" ],
      [ "Scatter", "classCabana_1_1Scatter.html", "classCabana_1_1Scatter" ],
      [ "SecondNeighborsTag", "classCabana_1_1SecondNeighborsTag.html", null ],
      [ "SerialOpTag", "classCabana_1_1SerialOpTag.html", null ],
      [ "SimdPolicy", "classCabana_1_1SimdPolicy.html", "classCabana_1_1SimdPolicy" ],
      [ "Slice", "classCabana_1_1Slice.html", "classCabana_1_1Slice" ],
      [ "SoA", "structCabana_1_1SoA.html", null ],
      [ "SoA< MemberTypes< Types... >, VectorLength >", "structCabana_1_1SoA_3_01MemberTypes_3_01Types_8_8_8_01_4_00_01VectorLength_01_4.html", "structCabana_1_1SoA_3_01MemberTypes_3_01Types_8_8_8_01_4_00_01VectorLength_01_4" ],
      [ "TeamOpTag", "classCabana_1_1TeamOpTag.html", null ],
      [ "TeamVectorOpTag", "classCabana_1_1TeamVectorOpTag.html", null ],
      [ "Tuple", "structCabana_1_1Tuple.html", null ],
      [ "Tuple< MemberTypes< Types... > >", "structCabana_1_1Tuple_3_01MemberTypes_3_01Types_8_8_8_01_4_01_4.html", "structCabana_1_1Tuple_3_01MemberTypes_3_01Types_8_8_8_01_4_01_4" ],
      [ "TypeIndexer", "structCabana_1_1TypeIndexer.html", null ],
      [ "VerletLayout2D", "structCabana_1_1VerletLayout2D.html", null ],
      [ "VerletLayoutCSR", "structCabana_1_1VerletLayoutCSR.html", null ],
      [ "VerletList", "classCabana_1_1VerletList.html", "classCabana_1_1VerletList" ],
      [ "VerletListData", "structCabana_1_1VerletListData.html", null ],
      [ "VerletListData< MemorySpace, VerletLayout2D >", "structCabana_1_1VerletListData_3_01MemorySpace_00_01VerletLayout2D_01_4.html", "structCabana_1_1VerletListData_3_01MemorySpace_00_01VerletLayout2D_01_4" ],
      [ "VerletListData< MemorySpace, VerletLayoutCSR >", "structCabana_1_1VerletListData_3_01MemorySpace_00_01VerletLayoutCSR_01_4.html", "structCabana_1_1VerletListData_3_01MemorySpace_00_01VerletLayoutCSR_01_4" ]
    ] ],
    [ "Kokkos", null, [
      [ "LayoutCabanaSlice", "structKokkos_1_1LayoutCabanaSlice.html", "structKokkos_1_1LayoutCabanaSlice" ]
    ] ]
];