pkg_check_modules(PC_HDF5 hdf5 QUIET)

find_path(HDF5_INCLUDE_DIR hdf5.h  HINTS ${PC_HDF5_INCLUDE_DIRS})
find_library(HDF5_LIBRARY NAMES hdf5 HINTS ${PC_HDF5_LIBRARY_DIRS})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(HDF5 DEFAULT_MSG HDF5_INCLUDE_DIR HDF5_LIBRARY)

mark_as_advanced(HDF5_INCLUDE_DIR HDF5_LIBRARY)

if(HDF5_INCLUDE_DIR AND HDF5_LIBRARY AND NOT TARGET HDF5::hdf5)
  add_library(HDF5::hdf5 UNKNOWN IMPORTED)
  set_target_properties(HDF5::hdf5 PROPERTIES
    IMPORTED_LOCATION ${HDF5_LIBRARY}
    INTERFACE_INCLUDE_DIRECTORIES ${HDF5_INCLUDE_DIR})
 # if(HDF5_LINK_FLAGS)
    set_property(TARGET HDF5::hdf5 APPEND_STRING PROPERTY INTERFACE_LINK_LIBRARIES "${HDF5_LIBRARY}")
 # endif()
endif()
message(STATUS "Found HDF5 library version ${HDF5_VERSION}")