find_package(PkgConfig QUIET)
pkg_check_modules(PC_HYPRE HYPRE QUIET)

find_path(HYPRE_INCLUDE_DIR HYPRE.h HINTS ${PC_HYPRE_INCLUDE_DIRS})
find_library(HYPRE_LIBRARY NAMES HYPRE HINTS ${PC_HYPRE_LIBRARY_DIRS})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(HYPRE DEFAULT_MSG HYPRE_INCLUDE_DIR HYPRE_LIBRARY)

mark_as_advanced(HYPRE_INCLUDE_DIR HYPRE_LIBRARY)

if(HYPRE_INCLUDE_DIR AND HYPRE_LIBRARY)
  add_library(HYPRE::hypre UNKNOWN IMPORTED)
  set_target_properties(HYPRE::hypre PROPERTIES
    IMPORTED_LOCATION ${HYPRE_LIBRARY}
    INTERFACE_INCLUDE_DIRECTORIES ${HYPRE_INCLUDE_DIR})
  if(HYPRE_LINK_FLAGS)
    set_property(TARGET HYPRE::hypre APPEND_STRING PROPERTY INTERFACE_LINK_LIBRARIES " ${HYPRE_LINK_FLAGS}")
  endif()
endif()
